from .helpers import *
from .auth import *
from .base import *
from .entidades import *
from .personal import *
from .tramites import *
from .reportes import *
from .ajax import *
from .vacancias import *
from .kardex import *
from .pendientes import *
from .correspondencia import *
from .roles import *
from .mensajeria import *
