# Generated by Django 5.2.6 on 2025-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio de Prelación')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP del Aspirante')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Aspirante')),
                ('tipo_val', models.CharField(max_length=255, verbose_name='Tipo de Valoración')),
            ],
            options={
                'verbose_name': 'Registro de Prelación',
                'verbose_name_plural': 'Registros de Prelación',
                'ordering': ['folio'],
            },
        ),
    ]
