# Generated by Django 5.2.6 on 2025-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0002_prelacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prelacion',
            options={'ordering': ['pos_orden'], 'verbose_name': 'Registro de Prelación', 'verbose_name_plural': 'Registros de Prelación'},
        ),
        migrations.AddField(
            model_name='prelacion',
            name='pos_orden',
            field=models.IntegerField(default=1, verbose_name='Posición de Orden'),
            preserve_default=False,
        ),
    ]
