# Generated by Django 5.2.6 on 2025-09-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0003_alter_prelacion_options_prelacion_pos_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillatramite',
            name='tipo_documento',
            field=models.CharField(choices=[('OFICIO', 'Oficio'), ('TRAMITE', 'Trámite')], default='TRAMITE', help_text='Indica si la plantilla es para un Oficio o un Trámite general.', max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
