# Generated by Django 5.0.7 on 2025-09-25 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0004_plantillatramite_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteReporteVacancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_generado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Generación')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('GENERADO', 'Generado')], default='EN_PROCESO', max_length=20, verbose_name='Estado')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='tramites_generados/vacancias/', verbose_name='Archivo Generado')),
                ('usuario_generador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Generador')),
            ],
            options={
                'verbose_name': 'Lote de Reporte de Vacancia',
                'verbose_name_plural': 'Lotes de Reportes de Vacancia',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoApreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(unique=True, verbose_name='Descripción de Apreciación')),
            ],
            options={
                'verbose_name': 'Tipo de Apreciación',
                'verbose_name_plural': 'Tipos de Apreciación',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Vacancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vacante', models.CharField(max_length=100, verbose_name='Tipo de Vacante')),
                ('tipo_movimiento_original', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo del Movimiento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(null=True, verbose_name='Fecha Final')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nombre_interino', models.CharField(blank=True, max_length=255, null=True)),
                ('curp_interino', models.CharField(blank=True, max_length=18, null=True)),
                ('nivel', models.CharField(default='Educación Especial', max_length=100)),
                ('entidad', models.CharField(default='DURANGO', max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('region', models.CharField(default='Durango', max_length=100)),
                ('zona_economica', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_plaza', models.CharField(max_length=50)),
                ('horas', models.CharField(blank=True, max_length=10, null=True)),
                ('sostenimiento', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('clave_presupuestal', models.CharField(max_length=100)),
                ('techo_financiero', models.CharField(max_length=50)),
                ('clave_ct', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=50)),
                ('tipo_movimiento_reporte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Movimiento para Reporte')),
                ('nombre_titular_reporte', models.CharField(max_length=255)),
                ('apreciacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.tipoapreciacion', verbose_name='Apreciación')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancias', to='gestion_escolar.lotereportevacancia', verbose_name='Lote de Reporte')),
                ('maestro_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.maestro', verbose_name='Maestro Titular')),
            ],
            options={
                'verbose_name': 'Vacancia',
                'verbose_name_plural': 'Vacancias',
                'ordering': ['-lote__fecha_creacion'],
            },
        ),
    ]
