# Generated by Django 5.0.7 on 2025-09-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0006_populate_tipoapreciacion'),
        ('gestion_escolar', '0005_populate_tipoapreciacion'),
    ]

    operations = []
