# Generated by Django 5.2.6 on 2025-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancia',
            name='tipo_movimiento_original',
            field=models.CharField(choices=[('LICENCIA POR ASUNTOS PARTICULARES', 'LICENCIA POR ASUNTOS PARTICULARES'), ('LICENCIA POR PASAR A OTRO EMPLEO', 'LICENCIA POR PASAR A OTRO EMPLEO'), ('LICENCIA POR COMISION SINDICAL O ELECCION POPULAR', 'LICENCIA POR COMISION SINDICAL O ELECCION POPULAR'), ('LICENCIA POR GRAVIDEZ', 'LICENCIA POR GRAVIDEZ'), ('LICENCIA POR INCAPACIDAD MEDICA', 'LICENCIA POR INCAPACIDAD MEDICA'), ('LICENCIA POR BECA', 'LICENCIA POR BECA'), ('LICENCIA PREPENSIONARIA', 'LICENCIA PREPENSIONARIA'), ('LICENCIA SIN GOCE DE SUELDO', 'LICENCIA SIN GOCE DE SUELDO')], max_length=100, verbose_name='Motivo del Movimiento'),
        ),
        migrations.AlterField(
            model_name='vacancia',
            name='tipo_vacante',
            field=models.CharField(choices=[('TEMPORAL', 'Temporal'), ('DEFINITIVA', 'Definitiva')], max_length=100, verbose_name='Tipo de Vacante'),
        ),
    ]
