# Generated by Django 5.2.6 on 2025-09-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0008_alter_vacancia_tipo_movimiento_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancia',
            name='maestro_interino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancias_interino', to='gestion_escolar.maestro', verbose_name='Maestro Interino'),
        ),
        migrations.AlterField(
            model_name='vacancia',
            name='curp_interino',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP Interino (manual)'),
        ),
        migrations.AlterField(
            model_name='vacancia',
            name='nombre_interino',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Interino (manual)'),
        ),
    ]
