# Generated by Django 5.2.6 on 2025-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0009_vacancia_maestro_interino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancia',
            name='pseudoplaza',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Pseudoplaza'),
        ),
    ]
