# Generated by Django 5.2.6 on 2025-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0010_vacancia_pseudoplaza'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancia',
            name='folio_prelacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio de Prelación'),
        ),
        migrations.AddField(
            model_name='vacancia',
            name='posicion_orden',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Posición de Orden (Prelación)'),
        ),
    ]
