# Generated by Django 5.2.6 on 2025-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0013_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
