# Generated by Django 5.2.6 on 2025-09-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0014_historial_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='lote_reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.lotereportevacancia', verbose_name='Lote de Reporte'),
        ),
        migrations.AddField(
            model_name='historial',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo'),
        ),
    ]
