# Generated by Django 5.2.6 on 2025-09-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0015_historial_lote_reporte_historial_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='datos_tramite',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos del Trámite/Oficio'),
        ),
    ]
