# Generated by Django 5.2.6 on 2025-09-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0016_historial_datos_tramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='maestro_secundario_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maestro Interino/Secundario'),
        ),
    ]
