# Generated by Django 5.2.6 on 2025-09-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0017_historial_maestro_secundario_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('TALON_PAGO', 'Talón de Pago'), ('ACTA_NACIMIENTO', 'Acta de Nacimiento'), ('INE', 'INE'), ('CURP_DOC', 'CURP (Documento)'), ('OFICIO_PRESENTACION', 'Oficio de Presentación'), ('FUP', 'FUP'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='expedientes/%Y/%m/%d/', verbose_name='Archivo PDF')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_expediente', to='gestion_escolar.maestro', verbose_name='Maestro')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento de Expediente',
                'verbose_name_plural': 'Documentos de Expediente',
                'ordering': ['maestro__a_paterno', 'tipo_documento', '-fecha_subida'],
                'unique_together': {('maestro', 'tipo_documento', 'archivo')},
            },
        ),
    ]
