# Generated by Django 5.2.6 on 2025-10-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0021_correspondencia_notificacion_pendiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='url_destino',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='correspondencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.correspondencia', verbose_name='Mensaje Relacionado'),
        ),
    ]
