# Generated by Django 5.2.6 on 2025-10-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0022_remove_notificacion_url_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'funcion__in': ['SUPERVISOR', 'SUPERVISOR (A)', 'SUPERVISOR(A)']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_supervisadas', to='gestion_escolar.maestro', verbose_name='Supervisor'),
        ),
    ]
