# Generated by Django 5.2.6 on 2025-10-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0023_zona_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(verbose_name='Fecha de Recibido')),
                ('fecha_oficio', models.DateField(verbose_name='Fecha del Oficio')),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Oficio'), ('TARJETA', 'Tarjeta'), ('CIRCULAR', 'Circular'), ('INVITACION', 'Invitación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('folio_documento', models.CharField(blank=True, max_length=100, verbose_name='Folio del Documento')),
                ('remitente', models.CharField(max_length=255, verbose_name='Remitente (De)')),
                ('contenido', models.TextField(verbose_name='Contenido del Oficio')),
                ('area', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('ACADEMICA', 'Académica'), ('DIRECCION', 'Dirección'), ('OTRO', 'Otro')], max_length=20, verbose_name='Área Destino')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='correspondencia/', verbose_name='Archivo Adjunto (PDF)')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencia_recibida', to='gestion_escolar.maestro', verbose_name='Maestro Relacionado (Opcional)')),
            ],
            options={
                'verbose_name': 'Registro de Correspondencia',
                'verbose_name_plural': 'Registros de Correspondencia',
                'ordering': ['-fecha_recibido', '-fecha_registro'],
            },
        ),
    ]
