# Generated by Django 5.2.6 on 2025-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0024_registrocorrespondencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloAjustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Ajustes',
                'permissions': (('acceder_ajustes', 'Puede acceder al módulo de Ajustes'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloBandejaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Bandeja de Entrada',
                'permissions': (('acceder_bandeja_entrada', 'Puede acceder a la Bandeja de Entrada'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Historial',
                'permissions': (('acceder_historial', 'Puede acceder al módulo de Historial'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloOficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Oficios',
                'permissions': (('acceder_oficios', 'Puede acceder al módulo de Oficios'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloTramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Trámites',
                'permissions': (('acceder_tramites', 'Puede acceder al módulo de Trámites'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloVacancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Asignación de Vacancia',
                'permissions': (('acceder_vacancias', 'Puede acceder al módulo de Asignación de Vacancia'),),
                'managed': False,
            },
        ),
    ]
