# Generated by Django 5.2.6 on 2025-10-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0025_moduloajustes_modulobandejaentrada_modulohistorial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloMisPendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Mis Pendientes',
                'permissions': (('acceder_pendientes', 'Puede acceder al módulo de Mis Pendientes'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Reportes',
                'permissions': (('acceder_reportes', 'Puede acceder al módulo de Reportes'),),
                'managed': False,
            },
        ),
    ]
