# Generated by Django 5.2.6 on 2025-10-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0026_modulomispendientes_moduloreportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocorrespondencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='correspondencia/', verbose_name='Archivo Adjunto (PDF)'),
        ),
    ]
