# Generated by Django 5.2.6 on 2025-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0027_registrocorrespondencia_archivo_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocorrespondencia',
            name='quien_recibio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quien Recibió'),
        ),
    ]
