# Generated by Django 5.2.6 on 2025-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0031_alter_vacancia_tipo_movimiento_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancia',
            name='fecha_final',
            field=models.DateField(null=True, verbose_name='Fecha Final'),
        ),
    ]
