# Generated by Django 5.2.6 on 2025-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0032_alter_vacancia_fecha_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancia',
            name='tipo_movimiento_reporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Movimiento para Reporte'),
        ),
    ]
