# Generated by Django 5.2.6 on 2025-10-30 17:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0033_alter_vacancia_tipo_movimiento_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tema')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='themes/', verbose_name='Imagen de Fondo (Opcional)')),
                ('color_principal', colorfield.fields.ColorField(default='#2c3e50', image_field=None, max_length=25, samples=None, verbose_name='Color Principal (Gradiente Superior)')),
                ('color_secundario', colorfield.fields.ColorField(default='#34495e', image_field=None, max_length=25, samples=None, verbose_name='Color Secundario (Gradiente Inferior)')),
                ('color_texto', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color del Texto')),
                ('activo', models.BooleanField(default=True, help_text='Solo un tema puede estar activo a la vez para un rango de fechas.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tema de Personalización',
                'verbose_name_plural': 'Temas de Personalización',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
