# Generated by Django 5.2.6 on 2025-11-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0035_alter_maestro_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'funcion__in': ['SUPERVISOR(A)']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_supervisadas', to='gestion_escolar.maestro', verbose_name='Supervisor'),
        ),
    ]
