# Generated by Django 5.0.7 on 2025-11-05 16:00

from django.db import migrations

def update_supervisor_value(apps, schema_editor):
    Maestro = apps.get_model('gestion_escolar', 'Maestro')
    Maestro.objects.filter(funcion='SUPERVISOR (A)').update(funcion='SUPERVISOR(A)')

def reverse_update(apps, schema_editor):
    Maestro = apps.get_model('gestion_escolar', 'Maestro')
    Maestro.objects.filter(funcion='SUPERVISOR(A)').update(funcion='SUPERVISOR (A)')

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0036_alter_zona_supervisor'),
    ]

    operations = [
        migrations.RunPython(update_supervisor_value, reverse_update),
    ]
