# Generated by Django 5.2.6 on 2025-11-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0037_update_supervisor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='a_materno_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='a_paterno_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='nombre_completo_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=202, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='nombre_completo_unaccented',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='nombres_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='nivel_estudio',
            field=models.CharField(blank=True, choices=[('DRA.', 'DRA.'), ('PROFRA.', 'PROFRA.'), ('PROF.', 'PROF.'), ('MTRA.', 'MTRA.'), ('PROFR.', 'PROFR.'), ('PSIC.', 'PSIC.'), ('DR.', 'DR.'), ('MTRO.', 'MTRO.'), ('C.', 'C.')], max_length=20, null=True, verbose_name='Titulo o Tratamiento (Prefijo a usar)'),
        ),
    ]
