# Generated by Django 5.2.6 on 2025-11-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0027_registrocorrespondencia_archivo_adjunto'),
        ('gestion_escolar', '0038_maestro_a_materno_normalized_and_more'),
    ]

    operations = [
    ]
