# Generated by Django 5.2.6 on 2025-11-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0039_merge_20251118_0826'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(editable=False, max_length=250, verbose_name='Nombre Completo')),
                ('rfc', models.CharField(blank=True, editable=False, max_length=13, null=True, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, editable=False, max_length=18, null=True, verbose_name='CURP')),
                ('clave_presupuestal', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Clave Presupuestal')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de FUP')),
                ('techo_financiero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Techo Financiero')),
                ('efectos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Efectos')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('sostenimiento', models.CharField(blank=True, choices=[('FEDERAL', 'Federal'), ('ESTATAL', 'Estatal')], max_length=10, null=True, verbose_name='Sostenimiento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='fups/%Y/%m/', verbose_name='Archivo PDF')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fups', to='gestion_escolar.maestro', verbose_name='Maestro')),
            ],
            options={
                'verbose_name': 'FUP',
                'verbose_name_plural': 'FUPs',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
