# Generated by Django 5.2.6 on 2025-11-26 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0040_fup_kardexmovimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloFUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de FUP',
                'permissions': (('acceder_fup', 'Puede acceder al módulo de FUP'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KardexMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción del Movimiento')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.maestro', verbose_name='Maestro')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': 'Movimientos de Kardex',
                'ordering': ['-fecha'],
            },
        ),
    ]
