# Generated by Django 5.2.6 on 2025-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0041_modulofup_kardexmovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='usar_filtro_oscuro',
            field=models.BooleanField(default=True, help_text='Si está activo, se aplicará un filtro oscuro sobre la imagen de fondo para mejorar la legibilidad del texto blanco.', verbose_name='Usar filtro oscuro en imagen'),
        ),
    ]
