# Generated by Django 5.2.6 on 2025-12-02 14:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0042_tema_usar_filtro_oscuro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='color_dropdown',
            field=colorfield.fields.ColorField(default='#3a506b', help_text='Color de fondo para los menús desplegables del sidebar', image_field=None, max_length=25, samples=None, verbose_name='Color de Fondo del Submenú'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='color_texto',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color del Texto del Sidebar'),
        ),
    ]
