# Generated by Django 5.2.6 on 2025-12-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0044_moduloprelacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuloPrelacion',
        ),
    ]
