# Generated by Django 5.2.6 on 2025-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0045_delete_moduloprelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloPrelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Prelación',
                'permissions': (('acceder_prelacion', 'Puede acceder al módulo de Prelación'),),
                'managed': False,
            },
        ),
    ]
