# Generated by Django 5.2.6 on 2026-01-22 15:53

from django.db import migrations

def crear_plantilla(apps, schema_editor):
    PlantillaTramite = apps.get_model('gestion_escolar', 'PlantillaTramite')
    PlantillaTramite.objects.create(
        nombre='CONSTANCIA DE CAMBIO',
        ruta_archivo='tramites/Plantillas/Word/constanciacambio.docx',
        tipo_documento='OFICIO'
    )



class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0046_moduloprelacion'),
    ]

    operations = [
        migrations.RunPython(crear_plantilla, migrations.RunPython.noop),
    ]
