# Generated by Django 5.2.6 on 2026-01-22 17:22

from django.db import migrations

def update_plantilla_ruta(apps, schema_editor):
    PlantillaTramite = apps.get_model('gestion_escolar', 'PlantillaTramite')
    try:
        plantilla = PlantillaTramite.objects.get(nombre='CONSTANCIA DE CAMBIO')
        plantilla.ruta_archivo = 'gestion_escolar/templates/tramites/Plantillas/Word/constanciacambio.docx'
        plantilla.save()
    except PlantillaTramite.DoesNotExist:
        pass # Handle case where plantilla might not exist (e.g., if previous migration was reverted)




class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0047_crear_plantilla_constancia_cambio'),
    ]

    operations = [
        migrations.RunPython(update_plantilla_ruta, migrations.RunPython.noop),
    ]
