# Generated by Django 5.2.6 on 2026-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0048_update_plantilla_constancia_cambio_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancia',
            name='plantilla_doc',
            field=models.CharField(choices=[('NORMAL', 'SOLICITUDASIGNACION.docx (Normal)'), ('NUMERO_36', 'SOLICITUDASIGNACION36.docx (Número 36)')], default='NORMAL', max_length=20, verbose_name='Plantilla de Oficio'),
        ),
    ]
