# Generated by Django 5.2.6 on 2026-02-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0049_vacancia_plantilla_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancia',
            name='plantilla_doc',
            field=models.CharField(choices=[('NORMAL', 'SOLICITUDASIGNACION.docx (Prorroga usar Art.3)'), ('NUMERO_36', 'SOLICITUDASIGNACION36.docx (No prorroga usar Art. 3)')], default='NORMAL', max_length=20, verbose_name='Plantilla de Oficio'),
        ),
    ]
