# Generated by Django 5.2.6 on 2026-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0051_alter_vacancia_plantilla_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso al Módulo de Kardex',
                'permissions': (('acceder_kardex', 'Puede acceder al módulo de Kardex'),),
                'managed': False,
            },
        ),
    ]
