# Generated by Django 5.2.6 on 2026-03-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0052_modulokardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='maestro_principal',
            field=models.ForeignKey(blank=True, help_text='Si este registro es una plaza adicional, seleccionar el registro principal del mismo maestro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plazas_secundarias', to='gestion_escolar.maestro', verbose_name='Plaza Principal'),
        ),
    ]
