# Generated by Django 5.2.6 on 2026-03-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0053_agregar_maestro_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='incentivo',
            field=models.CharField(blank=True, choices=[('', 'SIN INCENTIVO'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C'), ('7D', '7D'), ('K1', 'K1'), ('K1A', 'K1A'), ('K1B', 'K1B'), ('K1C', 'K1C'), ('KR', 'KR'), ('K4C', 'K4C'), ('A1', 'A1'), ('1B', '1B'), ('KU', 'KU'), ('O1', 'O1')], default='', max_length=10, null=True, verbose_name='Incentivo'),
        ),
    ]
