# Generated by Django 5.2.6 on 2026-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0054_maestro_incentivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Incentivo',
                'verbose_name_plural': 'Incentivos',
                'ordering': ['codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='incentivo',
        ),
        migrations.AddField(
            model_name='maestro',
            name='incentivos',
            field=models.ManyToManyField(blank=True, to='gestion_escolar.incentivo', verbose_name='Incentivos'),
        ),
    ]
