# Generated by Django 5.2.6 on 2026-07-03 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0055_incentivo_remove_maestro_incentivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maestro',
            constraint=models.UniqueConstraint(fields=('clave_presupuestal', 'curp', 'rfc', 'id_escuela', 'a_paterno', 'a_materno', 'nombres'), name='unique_maestro_completo', violation_error_message='Ya existe un maestro con esa misma clave presupuestal, CURP, RFC, escuela y nombre.'),
        ),
    ]
