# Generated by Django 5.2.6 on 2026-09-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0063_alter_maestro_funcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
