# Generated by Django 5.2.6 on 2026-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0065_normalizar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('LICENCIA', 'Licencia')], default='ACTIVO', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
