# Generated by Django 5.2.6 on 2026-09-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0068_vincular_maestro_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaRegular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(max_length=200, verbose_name='Nombre de la Escuela')),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TELESECUNDARIA', 'Telesecundaria')], max_length=20, verbose_name='Nivel')),
                ('subsistema', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTATAL', 'Estatal'), ('FED', 'Fed'), ('EST', 'Est')], max_length=20, verbose_name='Subsistema')),
                ('calle_num', models.CharField(blank=True, max_length=250, verbose_name='Calle y Número')),
                ('colonia', models.CharField(blank=True, max_length=150, verbose_name='Colonia')),
                ('cp', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('localidad', models.CharField(blank=True, max_length=150, verbose_name='Localidad')),
                ('municipio', models.CharField(blank=True, max_length=150, verbose_name='Municipio')),
                ('turno', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('M', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('V', 'Vespertino'), ('MATUTINO Y VESPERTINO', 'Matutino y Vespertino')], max_length=30, verbose_name='Turno')),
                ('supervisor', models.CharField(blank=True, max_length=200, verbose_name='Supervisor')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Director de la Escuela')),
                ('maestro_apoyo', models.CharField(blank=True, max_length=200, verbose_name='Maestro de Apoyo')),
                ('segundo_maestro_apoyo', models.CharField(blank=True, max_length=200, verbose_name='Segundo Maestro de Apoyo')),
                ('cct', models.ForeignKey(help_text='Centro de Trabajo FUA que atiende estas escuelas regulares', on_delete=django.db.models.deletion.CASCADE, related_name='escuelas_regulares', to='gestion_escolar.escuela', verbose_name='CCT (Centro de Trabajo)')),
            ],
            options={
                'verbose_name': 'Escuela Regular',
                'verbose_name_plural': 'Escuelas Regulares',
                'ordering': ['nivel', 'nombre_escuela'],
            },
        ),
    ]
