# Generated by Django 5.2.6 on 2026-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0069_escuelaregular'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelacion',
            name='telefonos',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Teléfonos'),
        ),
    ]
