# Generated by Django 5.2.6 on 2026-09-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0070_prelacion_telefonos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='horas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Horas'),
        ),
    ]
