# Generated by Django 5.2.6 on 2026-09-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0071_categoria_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interinato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_presupuestal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave Presupuestal Cubierta')),
                ('techo_financiero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Techo Financiero')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(blank=True, help_text='Dejar vacío si el interinato continúa vigente.', null=True, verbose_name='Fecha Final')),
                ('motivo', models.CharField(blank=True, choices=[('LICENCIA POR ASUNTOS PARTICULARES', 'LICENCIA POR ASUNTOS PARTICULARES'), ('LICENCIA POR PASAR A OTRO EMPLEO', 'LICENCIA POR PASAR A OTRO EMPLEO'), ('LICENCIA POR COMISION SINDICAL O ELECCION POPULAR', 'LICENCIA POR COMISION SINDICAL O ELECCION POPULAR'), ('LICENCIA POR GRAVIDEZ', 'LICENCIA POR GRAVIDEZ'), ('LICENCIA POR INCAPACIDAD MEDICA', 'LICENCIA POR INCAPACIDAD MEDICA'), ('LICENCIA POR BECA', 'LICENCIA POR BECA'), ('LICENCIA PREPENSIONARIA', 'LICENCIA PREPENSIONARIA'), ('LICENCIA SIN GOCE DE SUELDO', 'LICENCIA SIN GOCE DE SUELDO'), ('VACANTE DEFINITIVA', 'VACANTE DEFINITIVA'), ('NO ESPECIFICADO', 'NO ESPECIFICADO')], max_length=100, null=True, verbose_name='Motivo')),
                ('tipo', models.CharField(choices=[('INTERINO', 'Interino'), ('DESUBICADO', 'Desubicado'), ('REINGRESO', 'Reingreso'), ('FILIACION', 'Filiación')], default='INTERINO', max_length=20, verbose_name='Tipo de Asignación')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.escuela', verbose_name='Centro de Trabajo')),
                ('maestro_interino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interinatos_cubiertos', to='gestion_escolar.maestro', verbose_name='Maestro Interino')),
                ('maestro_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interinatos_titular', to='gestion_escolar.maestro', verbose_name='Maestro Titular Sustituido')),
                ('vacancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interinatos', to='gestion_escolar.vacancia', verbose_name='Vacancia Relacionada')),
            ],
            options={
                'verbose_name': 'Interinato',
                'verbose_name_plural': 'Historial de Interinatos',
                'ordering': ['-fecha_inicio', '-id'],
                'indexes': [models.Index(fields=['maestro_interino'], name='gestion_esc_maestro_2b707d_idx'), models.Index(fields=['estatus'], name='gestion_esc_estatus_2ff732_idx')],
            },
        ),
    ]
