# Generated by Django 6.1.1 on 2026-09-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0072_interinato'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='nombre',
            field=models.CharField(blank=True, help_text="Si se llena, se muestra en lugar de 'Zona N'. Ej. 'Departamento de Educación Especial', 'Zona 1 Laguna'.", max_length=120, verbose_name='Nombre de la zona (opcional)'),
        ),
        migrations.AlterField(
            model_name='lotereportevacancia',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('GENERADO', 'Generado'), ('PROCESANDO', 'Procesando'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=20, verbose_name='Estado'),
        ),
    ]
